server:
  port: ${ORDER_SERVICE_PORT:8081}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  application:
    name: cs-order-service
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.cs.order: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
