// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: milvus.proto

package io.milvus.grpc;

/**
 * Protobuf type {@code milvus.proto.milvus.MutationResult}
 */
public final class MutationResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:milvus.proto.milvus.MutationResult)
    MutationResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MutationResult.newBuilder() to construct.
  private MutationResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MutationResult() {
    succIndex_ = emptyIntList();
    errIndex_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MutationResult();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_MutationResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_MutationResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.milvus.grpc.MutationResult.class, io.milvus.grpc.MutationResult.Builder.class);
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private io.milvus.grpc.Status status_;
  /**
   * <code>.milvus.proto.common.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.milvus.proto.common.Status status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public io.milvus.grpc.Status getStatus() {
    return status_ == null ? io.milvus.grpc.Status.getDefaultInstance() : status_;
  }
  /**
   * <code>.milvus.proto.common.Status status = 1;</code>
   */
  @java.lang.Override
  public io.milvus.grpc.StatusOrBuilder getStatusOrBuilder() {
    return status_ == null ? io.milvus.grpc.Status.getDefaultInstance() : status_;
  }

  public static final int IDS_FIELD_NUMBER = 2;
  private io.milvus.grpc.IDs iDs_;
  /**
   * <pre>
   * required for insert, delete, upsert
   * </pre>
   *
   * <code>.milvus.proto.schema.IDs IDs = 2;</code>
   * @return Whether the iDs field is set.
   */
  @java.lang.Override
  public boolean hasIDs() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * required for insert, delete, upsert
   * </pre>
   *
   * <code>.milvus.proto.schema.IDs IDs = 2;</code>
   * @return The iDs.
   */
  @java.lang.Override
  public io.milvus.grpc.IDs getIDs() {
    return iDs_ == null ? io.milvus.grpc.IDs.getDefaultInstance() : iDs_;
  }
  /**
   * <pre>
   * required for insert, delete, upsert
   * </pre>
   *
   * <code>.milvus.proto.schema.IDs IDs = 2;</code>
   */
  @java.lang.Override
  public io.milvus.grpc.IDsOrBuilder getIDsOrBuilder() {
    return iDs_ == null ? io.milvus.grpc.IDs.getDefaultInstance() : iDs_;
  }

  public static final int SUCC_INDEX_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList succIndex_ =
      emptyIntList();
  /**
   * <pre>
   * error indexes indicate
   * </pre>
   *
   * <code>repeated uint32 succ_index = 3;</code>
   * @return A list containing the succIndex.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getSuccIndexList() {
    return succIndex_;
  }
  /**
   * <pre>
   * error indexes indicate
   * </pre>
   *
   * <code>repeated uint32 succ_index = 3;</code>
   * @return The count of succIndex.
   */
  public int getSuccIndexCount() {
    return succIndex_.size();
  }
  /**
   * <pre>
   * error indexes indicate
   * </pre>
   *
   * <code>repeated uint32 succ_index = 3;</code>
   * @param index The index of the element to return.
   * @return The succIndex at the given index.
   */
  public int getSuccIndex(int index) {
    return succIndex_.getInt(index);
  }
  private int succIndexMemoizedSerializedSize = -1;

  public static final int ERR_INDEX_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList errIndex_ =
      emptyIntList();
  /**
   * <pre>
   * error indexes indicate
   * </pre>
   *
   * <code>repeated uint32 err_index = 4;</code>
   * @return A list containing the errIndex.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getErrIndexList() {
    return errIndex_;
  }
  /**
   * <pre>
   * error indexes indicate
   * </pre>
   *
   * <code>repeated uint32 err_index = 4;</code>
   * @return The count of errIndex.
   */
  public int getErrIndexCount() {
    return errIndex_.size();
  }
  /**
   * <pre>
   * error indexes indicate
   * </pre>
   *
   * <code>repeated uint32 err_index = 4;</code>
   * @param index The index of the element to return.
   * @return The errIndex at the given index.
   */
  public int getErrIndex(int index) {
    return errIndex_.getInt(index);
  }
  private int errIndexMemoizedSerializedSize = -1;

  public static final int ACKNOWLEDGED_FIELD_NUMBER = 5;
  private boolean acknowledged_ = false;
  /**
   * <code>bool acknowledged = 5;</code>
   * @return The acknowledged.
   */
  @java.lang.Override
  public boolean getAcknowledged() {
    return acknowledged_;
  }

  public static final int INSERT_CNT_FIELD_NUMBER = 6;
  private long insertCnt_ = 0L;
  /**
   * <code>int64 insert_cnt = 6;</code>
   * @return The insertCnt.
   */
  @java.lang.Override
  public long getInsertCnt() {
    return insertCnt_;
  }

  public static final int DELETE_CNT_FIELD_NUMBER = 7;
  private long deleteCnt_ = 0L;
  /**
   * <code>int64 delete_cnt = 7;</code>
   * @return The deleteCnt.
   */
  @java.lang.Override
  public long getDeleteCnt() {
    return deleteCnt_;
  }

  public static final int UPSERT_CNT_FIELD_NUMBER = 8;
  private long upsertCnt_ = 0L;
  /**
   * <code>int64 upsert_cnt = 8;</code>
   * @return The upsertCnt.
   */
  @java.lang.Override
  public long getUpsertCnt() {
    return upsertCnt_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 9;
  private long timestamp_ = 0L;
  /**
   * <code>uint64 timestamp = 9;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getStatus());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getIDs());
    }
    if (getSuccIndexList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(succIndexMemoizedSerializedSize);
    }
    for (int i = 0; i < succIndex_.size(); i++) {
      output.writeUInt32NoTag(succIndex_.getInt(i));
    }
    if (getErrIndexList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(errIndexMemoizedSerializedSize);
    }
    for (int i = 0; i < errIndex_.size(); i++) {
      output.writeUInt32NoTag(errIndex_.getInt(i));
    }
    if (acknowledged_ != false) {
      output.writeBool(5, acknowledged_);
    }
    if (insertCnt_ != 0L) {
      output.writeInt64(6, insertCnt_);
    }
    if (deleteCnt_ != 0L) {
      output.writeInt64(7, deleteCnt_);
    }
    if (upsertCnt_ != 0L) {
      output.writeInt64(8, upsertCnt_);
    }
    if (timestamp_ != 0L) {
      output.writeUInt64(9, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatus());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getIDs());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < succIndex_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(succIndex_.getInt(i));
      }
      size += dataSize;
      if (!getSuccIndexList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      succIndexMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < errIndex_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(errIndex_.getInt(i));
      }
      size += dataSize;
      if (!getErrIndexList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      errIndexMemoizedSerializedSize = dataSize;
    }
    if (acknowledged_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, acknowledged_);
    }
    if (insertCnt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, insertCnt_);
    }
    if (deleteCnt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, deleteCnt_);
    }
    if (upsertCnt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, upsertCnt_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.milvus.grpc.MutationResult)) {
      return super.equals(obj);
    }
    io.milvus.grpc.MutationResult other = (io.milvus.grpc.MutationResult) obj;

    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasIDs() != other.hasIDs()) return false;
    if (hasIDs()) {
      if (!getIDs()
          .equals(other.getIDs())) return false;
    }
    if (!getSuccIndexList()
        .equals(other.getSuccIndexList())) return false;
    if (!getErrIndexList()
        .equals(other.getErrIndexList())) return false;
    if (getAcknowledged()
        != other.getAcknowledged()) return false;
    if (getInsertCnt()
        != other.getInsertCnt()) return false;
    if (getDeleteCnt()
        != other.getDeleteCnt()) return false;
    if (getUpsertCnt()
        != other.getUpsertCnt()) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasIDs()) {
      hash = (37 * hash) + IDS_FIELD_NUMBER;
      hash = (53 * hash) + getIDs().hashCode();
    }
    if (getSuccIndexCount() > 0) {
      hash = (37 * hash) + SUCC_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getSuccIndexList().hashCode();
    }
    if (getErrIndexCount() > 0) {
      hash = (37 * hash) + ERR_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getErrIndexList().hashCode();
    }
    hash = (37 * hash) + ACKNOWLEDGED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAcknowledged());
    hash = (37 * hash) + INSERT_CNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInsertCnt());
    hash = (37 * hash) + DELETE_CNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDeleteCnt());
    hash = (37 * hash) + UPSERT_CNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpsertCnt());
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.milvus.grpc.MutationResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.milvus.grpc.MutationResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.milvus.grpc.MutationResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.milvus.grpc.MutationResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.milvus.grpc.MutationResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.milvus.grpc.MutationResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.milvus.grpc.MutationResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.milvus.grpc.MutationResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.milvus.grpc.MutationResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.milvus.grpc.MutationResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.milvus.grpc.MutationResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.milvus.grpc.MutationResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.milvus.grpc.MutationResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code milvus.proto.milvus.MutationResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:milvus.proto.milvus.MutationResult)
      io.milvus.grpc.MutationResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_MutationResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_MutationResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.milvus.grpc.MutationResult.class, io.milvus.grpc.MutationResult.Builder.class);
    }

    // Construct using io.milvus.grpc.MutationResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStatusFieldBuilder();
        getIDsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = null;
      if (statusBuilder_ != null) {
        statusBuilder_.dispose();
        statusBuilder_ = null;
      }
      iDs_ = null;
      if (iDsBuilder_ != null) {
        iDsBuilder_.dispose();
        iDsBuilder_ = null;
      }
      succIndex_ = emptyIntList();
      errIndex_ = emptyIntList();
      acknowledged_ = false;
      insertCnt_ = 0L;
      deleteCnt_ = 0L;
      upsertCnt_ = 0L;
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.milvus.grpc.MilvusProto.internal_static_milvus_proto_milvus_MutationResult_descriptor;
    }

    @java.lang.Override
    public io.milvus.grpc.MutationResult getDefaultInstanceForType() {
      return io.milvus.grpc.MutationResult.getDefaultInstance();
    }

    @java.lang.Override
    public io.milvus.grpc.MutationResult build() {
      io.milvus.grpc.MutationResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.milvus.grpc.MutationResult buildPartial() {
      io.milvus.grpc.MutationResult result = new io.milvus.grpc.MutationResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.milvus.grpc.MutationResult result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = statusBuilder_ == null
            ? status_
            : statusBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.iDs_ = iDsBuilder_ == null
            ? iDs_
            : iDsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        succIndex_.makeImmutable();
        result.succIndex_ = succIndex_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        errIndex_.makeImmutable();
        result.errIndex_ = errIndex_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.acknowledged_ = acknowledged_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.insertCnt_ = insertCnt_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.deleteCnt_ = deleteCnt_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.upsertCnt_ = upsertCnt_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.timestamp_ = timestamp_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.milvus.grpc.MutationResult) {
        return mergeFrom((io.milvus.grpc.MutationResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.milvus.grpc.MutationResult other) {
      if (other == io.milvus.grpc.MutationResult.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.hasIDs()) {
        mergeIDs(other.getIDs());
      }
      if (!other.succIndex_.isEmpty()) {
        if (succIndex_.isEmpty()) {
          succIndex_ = other.succIndex_;
          succIndex_.makeImmutable();
          bitField0_ |= 0x00000004;
        } else {
          ensureSuccIndexIsMutable();
          succIndex_.addAll(other.succIndex_);
        }
        onChanged();
      }
      if (!other.errIndex_.isEmpty()) {
        if (errIndex_.isEmpty()) {
          errIndex_ = other.errIndex_;
          errIndex_.makeImmutable();
          bitField0_ |= 0x00000008;
        } else {
          ensureErrIndexIsMutable();
          errIndex_.addAll(other.errIndex_);
        }
        onChanged();
      }
      if (other.getAcknowledged() != false) {
        setAcknowledged(other.getAcknowledged());
      }
      if (other.getInsertCnt() != 0L) {
        setInsertCnt(other.getInsertCnt());
      }
      if (other.getDeleteCnt() != 0L) {
        setDeleteCnt(other.getDeleteCnt());
      }
      if (other.getUpsertCnt() != 0L) {
        setUpsertCnt(other.getUpsertCnt());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getIDsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              int v = input.readUInt32();
              ensureSuccIndexIsMutable();
              succIndex_.addInt(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureSuccIndexIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                succIndex_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            } // case 26
            case 32: {
              int v = input.readUInt32();
              ensureErrIndexIsMutable();
              errIndex_.addInt(v);
              break;
            } // case 32
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureErrIndexIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                errIndex_.addInt(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            } // case 34
            case 40: {
              acknowledged_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              insertCnt_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              deleteCnt_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              upsertCnt_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              timestamp_ = input.readUInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.milvus.grpc.Status status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.milvus.grpc.Status, io.milvus.grpc.Status.Builder, io.milvus.grpc.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.milvus.proto.common.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.milvus.proto.common.Status status = 1;</code>
     * @return The status.
     */
    public io.milvus.grpc.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? io.milvus.grpc.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.milvus.proto.common.Status status = 1;</code>
     */
    public Builder setStatus(io.milvus.grpc.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
      } else {
        statusBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.milvus.proto.common.Status status = 1;</code>
     */
    public Builder setStatus(
        io.milvus.grpc.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.milvus.proto.common.Status status = 1;</code>
     */
    public Builder mergeStatus(io.milvus.grpc.Status value) {
      if (statusBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          status_ != null &&
          status_ != io.milvus.grpc.Status.getDefaultInstance()) {
          getStatusBuilder().mergeFrom(value);
        } else {
          status_ = value;
        }
      } else {
        statusBuilder_.mergeFrom(value);
      }
      if (status_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.milvus.proto.common.Status status = 1;</code>
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = null;
      if (statusBuilder_ != null) {
        statusBuilder_.dispose();
        statusBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.milvus.proto.common.Status status = 1;</code>
     */
    public io.milvus.grpc.Status.Builder getStatusBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.milvus.proto.common.Status status = 1;</code>
     */
    public io.milvus.grpc.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            io.milvus.grpc.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.milvus.proto.common.Status status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.milvus.grpc.Status, io.milvus.grpc.Status.Builder, io.milvus.grpc.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.milvus.grpc.Status, io.milvus.grpc.Status.Builder, io.milvus.grpc.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private io.milvus.grpc.IDs iDs_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.milvus.grpc.IDs, io.milvus.grpc.IDs.Builder, io.milvus.grpc.IDsOrBuilder> iDsBuilder_;
    /**
     * <pre>
     * required for insert, delete, upsert
     * </pre>
     *
     * <code>.milvus.proto.schema.IDs IDs = 2;</code>
     * @return Whether the iDs field is set.
     */
    public boolean hasIDs() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * required for insert, delete, upsert
     * </pre>
     *
     * <code>.milvus.proto.schema.IDs IDs = 2;</code>
     * @return The iDs.
     */
    public io.milvus.grpc.IDs getIDs() {
      if (iDsBuilder_ == null) {
        return iDs_ == null ? io.milvus.grpc.IDs.getDefaultInstance() : iDs_;
      } else {
        return iDsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * required for insert, delete, upsert
     * </pre>
     *
     * <code>.milvus.proto.schema.IDs IDs = 2;</code>
     */
    public Builder setIDs(io.milvus.grpc.IDs value) {
      if (iDsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        iDs_ = value;
      } else {
        iDsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * required for insert, delete, upsert
     * </pre>
     *
     * <code>.milvus.proto.schema.IDs IDs = 2;</code>
     */
    public Builder setIDs(
        io.milvus.grpc.IDs.Builder builderForValue) {
      if (iDsBuilder_ == null) {
        iDs_ = builderForValue.build();
      } else {
        iDsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * required for insert, delete, upsert
     * </pre>
     *
     * <code>.milvus.proto.schema.IDs IDs = 2;</code>
     */
    public Builder mergeIDs(io.milvus.grpc.IDs value) {
      if (iDsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          iDs_ != null &&
          iDs_ != io.milvus.grpc.IDs.getDefaultInstance()) {
          getIDsBuilder().mergeFrom(value);
        } else {
          iDs_ = value;
        }
      } else {
        iDsBuilder_.mergeFrom(value);
      }
      if (iDs_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * required for insert, delete, upsert
     * </pre>
     *
     * <code>.milvus.proto.schema.IDs IDs = 2;</code>
     */
    public Builder clearIDs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      iDs_ = null;
      if (iDsBuilder_ != null) {
        iDsBuilder_.dispose();
        iDsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * required for insert, delete, upsert
     * </pre>
     *
     * <code>.milvus.proto.schema.IDs IDs = 2;</code>
     */
    public io.milvus.grpc.IDs.Builder getIDsBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getIDsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * required for insert, delete, upsert
     * </pre>
     *
     * <code>.milvus.proto.schema.IDs IDs = 2;</code>
     */
    public io.milvus.grpc.IDsOrBuilder getIDsOrBuilder() {
      if (iDsBuilder_ != null) {
        return iDsBuilder_.getMessageOrBuilder();
      } else {
        return iDs_ == null ?
            io.milvus.grpc.IDs.getDefaultInstance() : iDs_;
      }
    }
    /**
     * <pre>
     * required for insert, delete, upsert
     * </pre>
     *
     * <code>.milvus.proto.schema.IDs IDs = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.milvus.grpc.IDs, io.milvus.grpc.IDs.Builder, io.milvus.grpc.IDsOrBuilder> 
        getIDsFieldBuilder() {
      if (iDsBuilder_ == null) {
        iDsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.milvus.grpc.IDs, io.milvus.grpc.IDs.Builder, io.milvus.grpc.IDsOrBuilder>(
                getIDs(),
                getParentForChildren(),
                isClean());
        iDs_ = null;
      }
      return iDsBuilder_;
    }

    private com.google.protobuf.Internal.IntList succIndex_ = emptyIntList();
    private void ensureSuccIndexIsMutable() {
      if (!succIndex_.isModifiable()) {
        succIndex_ = makeMutableCopy(succIndex_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 succ_index = 3;</code>
     * @return A list containing the succIndex.
     */
    public java.util.List<java.lang.Integer>
        getSuccIndexList() {
      succIndex_.makeImmutable();
      return succIndex_;
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 succ_index = 3;</code>
     * @return The count of succIndex.
     */
    public int getSuccIndexCount() {
      return succIndex_.size();
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 succ_index = 3;</code>
     * @param index The index of the element to return.
     * @return The succIndex at the given index.
     */
    public int getSuccIndex(int index) {
      return succIndex_.getInt(index);
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 succ_index = 3;</code>
     * @param index The index to set the value at.
     * @param value The succIndex to set.
     * @return This builder for chaining.
     */
    public Builder setSuccIndex(
        int index, int value) {

      ensureSuccIndexIsMutable();
      succIndex_.setInt(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 succ_index = 3;</code>
     * @param value The succIndex to add.
     * @return This builder for chaining.
     */
    public Builder addSuccIndex(int value) {

      ensureSuccIndexIsMutable();
      succIndex_.addInt(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 succ_index = 3;</code>
     * @param values The succIndex to add.
     * @return This builder for chaining.
     */
    public Builder addAllSuccIndex(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureSuccIndexIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, succIndex_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 succ_index = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccIndex() {
      succIndex_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList errIndex_ = emptyIntList();
    private void ensureErrIndexIsMutable() {
      if (!errIndex_.isModifiable()) {
        errIndex_ = makeMutableCopy(errIndex_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 err_index = 4;</code>
     * @return A list containing the errIndex.
     */
    public java.util.List<java.lang.Integer>
        getErrIndexList() {
      errIndex_.makeImmutable();
      return errIndex_;
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 err_index = 4;</code>
     * @return The count of errIndex.
     */
    public int getErrIndexCount() {
      return errIndex_.size();
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 err_index = 4;</code>
     * @param index The index of the element to return.
     * @return The errIndex at the given index.
     */
    public int getErrIndex(int index) {
      return errIndex_.getInt(index);
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 err_index = 4;</code>
     * @param index The index to set the value at.
     * @param value The errIndex to set.
     * @return This builder for chaining.
     */
    public Builder setErrIndex(
        int index, int value) {

      ensureErrIndexIsMutable();
      errIndex_.setInt(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 err_index = 4;</code>
     * @param value The errIndex to add.
     * @return This builder for chaining.
     */
    public Builder addErrIndex(int value) {

      ensureErrIndexIsMutable();
      errIndex_.addInt(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 err_index = 4;</code>
     * @param values The errIndex to add.
     * @return This builder for chaining.
     */
    public Builder addAllErrIndex(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureErrIndexIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, errIndex_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * error indexes indicate
     * </pre>
     *
     * <code>repeated uint32 err_index = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrIndex() {
      errIndex_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private boolean acknowledged_ ;
    /**
     * <code>bool acknowledged = 5;</code>
     * @return The acknowledged.
     */
    @java.lang.Override
    public boolean getAcknowledged() {
      return acknowledged_;
    }
    /**
     * <code>bool acknowledged = 5;</code>
     * @param value The acknowledged to set.
     * @return This builder for chaining.
     */
    public Builder setAcknowledged(boolean value) {

      acknowledged_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool acknowledged = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAcknowledged() {
      bitField0_ = (bitField0_ & ~0x00000010);
      acknowledged_ = false;
      onChanged();
      return this;
    }

    private long insertCnt_ ;
    /**
     * <code>int64 insert_cnt = 6;</code>
     * @return The insertCnt.
     */
    @java.lang.Override
    public long getInsertCnt() {
      return insertCnt_;
    }
    /**
     * <code>int64 insert_cnt = 6;</code>
     * @param value The insertCnt to set.
     * @return This builder for chaining.
     */
    public Builder setInsertCnt(long value) {

      insertCnt_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 insert_cnt = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearInsertCnt() {
      bitField0_ = (bitField0_ & ~0x00000020);
      insertCnt_ = 0L;
      onChanged();
      return this;
    }

    private long deleteCnt_ ;
    /**
     * <code>int64 delete_cnt = 7;</code>
     * @return The deleteCnt.
     */
    @java.lang.Override
    public long getDeleteCnt() {
      return deleteCnt_;
    }
    /**
     * <code>int64 delete_cnt = 7;</code>
     * @param value The deleteCnt to set.
     * @return This builder for chaining.
     */
    public Builder setDeleteCnt(long value) {

      deleteCnt_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 delete_cnt = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeleteCnt() {
      bitField0_ = (bitField0_ & ~0x00000040);
      deleteCnt_ = 0L;
      onChanged();
      return this;
    }

    private long upsertCnt_ ;
    /**
     * <code>int64 upsert_cnt = 8;</code>
     * @return The upsertCnt.
     */
    @java.lang.Override
    public long getUpsertCnt() {
      return upsertCnt_;
    }
    /**
     * <code>int64 upsert_cnt = 8;</code>
     * @param value The upsertCnt to set.
     * @return This builder for chaining.
     */
    public Builder setUpsertCnt(long value) {

      upsertCnt_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 upsert_cnt = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpsertCnt() {
      bitField0_ = (bitField0_ & ~0x00000080);
      upsertCnt_ = 0L;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>uint64 timestamp = 9;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>uint64 timestamp = 9;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000100);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:milvus.proto.milvus.MutationResult)
  }

  // @@protoc_insertion_point(class_scope:milvus.proto.milvus.MutationResult)
  private static final io.milvus.grpc.MutationResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.milvus.grpc.MutationResult();
  }

  public static io.milvus.grpc.MutationResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MutationResult>
      PARSER = new com.google.protobuf.AbstractParser<MutationResult>() {
    @java.lang.Override
    public MutationResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MutationResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MutationResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.milvus.grpc.MutationResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

